### PR TITLE
Ep 18 header badge component

### PR DESCRIPTION
**Pull request by Highpriest26**

### CODE REVIEW

**Comment by Highpriest26** [comment]
Resolved

**Comment by Bluebberies** [comment]
Still not responsive for mobile

**Comment by Bluebberies** [comment]
@Highpriest26 
image

https://github.com/user-attachments/assets/5bb82cd1-3cd0-4c0f-aea5-436bd0f154cc

This is how your component looks for mobile. The Ui for the mobile is not ready yet but i dont thing it's cool to make it display col for mobile. The image should only get smaller but still the componenebt should stlll be flexed row. Also pass in optional classnames for the parent div and, image and title

**Comment by Highpriest26** [comment]
Resolved

**Comment by Bluebberies** [comment]
Please pull from dev branch and update your changes

**Pull request closed without merging**
