### PR TITLE
Ep-15-Icon-Component

### PR DESCRIPTION
**Pull request by Highpriest26**
Icon-Component

### CODE REVIEW

**Comment by Bluebberies** [comment]
@Highpriest26  check this branch again, you did not add all the assets before making a push.  Run """git add .""" and then commit then push

**Comment by Bluebberies** [comment]
@Highpriest26 nice job, but few modifications to be made
- make use of the clsx library and replace this conditionally class naming 
className={`flex items-center ${positionClasses[position]} ${className}`} to use it. It makes the codes cleaner.
- Remove unnecessary comments.
- Make sure that the icons have a pointer cursor and that the icon and text are center aligned
- Create props for titleClassname, iconClassname etc for my dynamism

**Comment by Bluebberies** [comment]
@Highpriest26, nice work but few corrections
- from this code
 ` className={clsx('flex items-center cursor-pointer', positionClasses[position], className)} `, since you are appending the className for it, i don't think there is a need for this `positionClasses[position]`. So you cabn get rid of it and pass all styles via the className prop. So get rid of the positionClasses too.
- You did this for the icon style too ` className={clsx(IconComponent, iconSize, iconClassName)}  `, since you are oassing down iconClassName as a props that can hold all possible styling, i don't think there is a need for the 'iconSize' too in there. So get rid of that also.
- In the title, you have this styling too `className={clsx(sizeClasses[size as keyof typeof sizeClasses], 'ml-2', titleClassName)} `, you can get rid of it and just make use of the titleClassName to pass down all styles for the title. 
- Get rid of the unnecessary props also. 
- We already have react-icons liobrary  installed and you installed "@fortawesome/fontawesome-free". For better modularity, let us stick to one library, so swicth to the react-icons library. 
- Your icon component be able to accept both images or icons optionally as thh icon type. So please look into it

**Comment by Highpriest26** [comment]
Resolved

**Pull request merged**
