### PR TITLE
Ep 14 user pill component

### PR DESCRIPTION
**Pull request by Highpriest26**

### CODE REVIEW

**Comment by Bluebberies** [comment]
@Highpriest26 few corrections
- There should be a default avatar image/icon for in the user pill component for the absence of the user's image
- There should be a default width in the parent div of the component to prevent overflow.
- The component should allow different className props e.g titleClassname, imageClassname, parentClassName etc.
- Please follow the design on figma.

**Comment by Highpriest26** [comment]
Resolve the issue

**Comment by Bluebberies** [comment]
@Highpriest26, 
- You did not add any default image

**Comment by Bluebberies** [comment]
Just take note of it

**Pull request merged**
